services:
  lensup.photocollectorservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8081
    container_name: lensup.photocollectorservice.api
    image: lensup.photocollectorservice.api
    build:
      context: ./backend-services
      dockerfile: photo-collector-service/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      
  lensup.photocollectorservice.ui:
    container_name: lensup.photocollectorservice.ui
    image: lensup.photocollectorservice.ui
    build:
      context: ./ui-applications/packages/photo-collector-ui
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  lensup.galleryservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8082
      - ASPNETCORE_HTTPS_PORT=8083
    container_name: lensup.galleryservice.api
    image: lensup.galleryservice.api
    build:
      context: ./backend-services
      dockerfile: gallery-service/Dockerfile
    ports:
      - "8082:8082"
      - "8083:8083"

  lensup.galleryservice.ui:
    container_name: lensup.galleryservice.ui
    image: lensup.galleryservice.ui
    build:
      context: ./ui-applications/packages/gallery-ui
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  lensup.backofficeservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8084
      - ASPNETCORE_HTTPS_PORT=8085
    container_name: lensup.backofficeservice.api
    image: lensup.backofficeservice.api
    build:
      context: ./backend-services
      dockerfile: back-office-service/Dockerfile
    ports:
      - "8084:8084"
      - "8085:8085"

  lensup.backofficeservice.ui:
    container_name: lensup.backofficeservice.ui
    image: lensup.backofficeservice.ui
    build:
      context: ./ui-applications/packages/back-office-ui
      dockerfile: Dockerfile
    ports:
      - "5000:5000"