services:
  lensup.photocollectorservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8081
    container_name: lensup.photocollectorservice.api
    image: lensup.photocollectorservice.api
    build:
      context: .
      dockerfile: backend-services/photo-collector-service/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"